TARGET_SAMPLE_RATE : 16000
NUM_SAMPLES : 16000
LABELS : ['eight','five','four','nine','one','seven','six','three','two','zero']
SPLIT_SIZE : 0.2
NUM_MFCC : 40
RANDOM_STATE : 0
FRAME_LENGTH : 1024
FRAME_STEP : 512
INPUT_LENGTH: 10000
BATCH_SIZE: 24
BUFFER_SIZE: 1000
