artifacts_root: artifacts

data_augmentation:
  root_dir: artifacts/data_ingestion/adr_ds
  src_dst_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDigitsAugmented

data_tf_ingestion:
 root_dir: artifacts/tf_ingestion/dataset
 source_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtCls\
 dst_path: artifacts/tf_ingestion/dataset

data_tf_training:
 root_dir: artifacts/tf_ingestion/dataset
 dst_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5

data_tf_evaluation:
 root_dir: artifacts/tf_ingestion
 data_path: artifacts/tf_ingestion/dataset/test_metadata.csv
 model_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5

data_tf_inference:
 root_dir: artifacts/tf_ingestion
 audio_path: artifacts/tf_ingestion/dataset/test_metadata.csv
 #audio_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtCls\eight\eight-t-6.wav
 model_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5
 
 #------------------------------------------------------------

data_ingestion:
  root_dir: artifacts/SeqDataset/data_ingestion
  source_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDigitsAugmented\wavs
  data_file: artifacts/SeqDataset/data_ingestion/adr_ds.npz

data_preprocessing:
  root_dir: artifacts/SeqDataset/data_ingestion
  source_path: artifacts/SeqDataset/data_ingestion/adr_ds.npz
  data_file: artifacts/SeqDataset/data_ingestion/adr_pca_ds.npz

data_training:
  root_dir: artifacts/SeqDataset/models
  origin_data_path: artifacts/SeqDataset/data_ingestion/adr_ds.npz
  dst_path: artifacts/SeqDataset/models/ardg_cnn_model.h5