artifacts_root: artifacts

data_augmentation:
  root_dir: artifacts/data_ingestion/adr_ds
  src_dst_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDigitsAugmented

data_tf_ingestion:
 root_dir: artifacts/tf_ingestion/dataset
 source_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtCls\
 dst_path: artifacts/tf_ingestion/dataset

data_tf_training:
 root_dir: artifacts/tf_ingestion/dataset
 dst_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5

data_tf_evaluation:
 root_dir: artifacts/tf_ingestion
 data_path: artifacts/tf_ingestion/dataset/test_metadata.csv
 model_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5

data_tf_inference:
 root_dir: artifacts/tf_ingestion
 audio_path: artifacts/tf_ingestion/dataset/test_metadata.csv
 #audio_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtCls\eight\eight-t-6.wav
 model_path: artifacts/tf_ingestion/models/ardg_cnn_model.h5
 
 #------------------------------------------------------------

data_ingestion:
  root_dir: artifacts/data_ingestion/adr_ds
  source_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtEnPool
  #arclasses_path: E:\MyOnlineCourses\ML_Projects\datasets\arabic_augmented_digits_wavs\
  arclasses_path: E:\MyOnlineCourses\ML_Projects\ADR\ArabDIGdtEn\
  data_file: artifacts/data_ingestion/adr_ds.npz
  csv_file : artifacts/data_ingestion/metadata.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  source_path: artifacts/data_ingestion/adr_ds.npz
  data_file: artifacts/data_preprocessing/adr_pca_ds.npz

data_preparation:
  root_dir: artifacts/data_preprocessing
  origin_data_path: artifacts/data_ingestion/adr_ds.npz
  processed_data_path: artifacts/data_preprocessing/adr_pca_ds.npz